#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

try:
    from packaging.utils import canonicalize_name, parse_wheel_filename
except ModuleNotFoundError:  # python-build-standalone bootstrap exposes pip's vendored copy.
    from pip._vendor.packaging.utils import canonicalize_name, parse_wheel_filename


def digest(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            value.update(chunk)
    return value.hexdigest()


def locked_requirements(path: Path) -> dict[str, tuple[str, str]]:
    result: dict[str, tuple[str, str]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        value = line.strip()
        if not value or value.startswith("#"):
            continue
        match = re.fullmatch(r"([A-Za-z0-9_.-]+)==([^\s]+)", value)
        if match is None:
            raise ValueError(f"Unsupported requirement line: {value}")
        name, version = match.groups()
        result[canonicalize_name(name)] = (name, version)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("wheelhouse", type=Path)
    parser.add_argument("requirements", type=Path)
    parser.add_argument("hash_lock", type=Path)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("source_json", type=Path)
    arguments = parser.parse_args()
    source_config = json.loads(arguments.source_json.read_text(encoding="utf-8"))
    sdists = {
        canonicalize_name(item["name"]): item for item in source_config.get("pythonSdists", [])
    }

    expected = locked_requirements(arguments.requirements)
    project_version = re.search(
        r'^version\s*=\s*["\']([^"\']+)',
        (arguments.source_json.parents[3] / "pyproject.toml").read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    if project_version is None:
        raise ValueError("Cannot determine the local project version from pyproject.toml")
    expected["xingyu-lyrics-aligner"] = (
        "xingyu-lyrics-aligner",
        project_version.group(1),
    )
    wheels: dict[str, tuple[Path, str, str, frozenset[object]]] = {}
    for wheel in sorted(arguments.wheelhouse.glob("*.whl")):
        name, version, _build, tags = parse_wheel_filename(wheel.name)
        canonical = canonicalize_name(name)
        if canonical in wheels:
            raise ValueError(f"Duplicate wheel for {canonical}: {wheel.name}")
        wheels[canonical] = (wheel, str(version), digest(wheel), tags)

    missing = sorted(set(expected) - set(wheels))
    unexpected = sorted(set(wheels) - set(expected))
    if missing or unexpected:
        raise ValueError(f"Wheelhouse mismatch: missing={missing}, unexpected={unexpected}")

    lock_lines = [
        "# Generated by scripts/prepare-macos-wheelhouse.sh --refresh-lock.",
        "# macOS arm64 / CPython 3.11 only; do not edit hashes by hand.",
    ]
    records: list[dict[str, object]] = []
    for canonical in sorted(expected):
        requested_name, expected_version = expected[canonical]
        wheel, actual_version, sha256, tags = wheels[canonical]
        if actual_version != expected_version:
            raise ValueError(
                f"Version mismatch for {requested_name}: {actual_version} != {expected_version}"
            )
        lock_lines.append(f"{requested_name}=={expected_version} --hash=sha256:{sha256}")
        tag_values = sorted(str(tag) for tag in tags)
        record: dict[str, object] = {
            "name": requested_name,
            "version": expected_version,
            "filename": wheel.name,
            "sha256": sha256,
            "sizeBytes": wheel.stat().st_size,
            "source": (
                "local-project-source"
                if canonical == "xingyu-lyrics-aligner"
                else f"https://pypi.org/simple/{canonical}/"
            ),
            "wheelTags": tag_values,
            "thinInstalledMachOToArm64": "universal2" in wheel.name,
        }
        if canonical in sdists:
            record["builtFromSdist"] = sdists[canonical]
        records.append(record)
    arguments.hash_lock.write_text("\n".join(lock_lines) + "\n", encoding="utf-8")
    payload = {
        "schemaVersion": 1,
        "platform": "macOS",
        "architecture": "arm64",
        "pythonVersion": "3.11.15",
        "index": "https://pypi.org/simple",
        "projectWheelBuiltFrom": "repository source with SOURCE_DATE_EPOCH",
        "wheels": records,
    }
    arguments.manifest.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
